### ISSUE TITLE
Quick slides: Sticky slides before title slides cause title slide to render incorrectly

### ISSUE THREAD

**Issue by dyc3** [StevensSEC/softe.club#219]
When there is a sticky default slide before a title slide, it will cause the title slide to be laid out incorrectly. The title slide will appear under the sticky slide, when it should appear to the right of it.

### Screenshots

![2020-10-17-100630_1895x893_scrot](https://user-images.githubusercontent.com/1808807/96339123-79b8ef80-1060-11eb-99e9-73c37de08c95.png)

### Minimum reproducible example

```yaml
slides:
  - content: |
      # Lorem ipsum dolor
      - Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      - enim ad minim veniam, quis nostrud exercitation ullamco
      - Nam at lectus urna duis convallis convallis tellus id interdum.
      - Egestas integer eget aliquet nibh praesent tristique magna sit.
    sticky: 2
  - type: title
    title: Slides Title
    subtitle: Slides subtitle
```
